sudo: enabled

  
language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - docker build -t portfolio-web .
  - docker run -d -p 5000:5000 portfolio-web
  - docker ps -a

script:
  - pytest